name: ollama-chat
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.32.0
    - ollama==0.3.0
    - watchdog==4.0.0
variables:
  # Streamlit設定
  STREAMLIT_SERVER_PORT: 8501
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: false