[server]
# ポート設定
port = 8501
# ヘッドレスで稼働（サーバ利用向け）
headless = true
# 保存時に再実行
runOnSave = true

[runner]
# マジックコマンドを無効化（警告削減）
magicEnabled = false
# Fast reruns
fastReruns = true

[theme]
# ダークテーマ設定（お好みで）
base = "dark"